name: slurm_server_manager
description: Mobile app to monitor slurm clusters
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  logger: ^1.4.0
  cupertino_back_gesture: ^0.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  json_theme: ^5.0.2+4
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/arimo/Arimo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arimo/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arimo/Arimo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/arimo/Arimo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true