name: slurm_server_manager
description: Monitoring slurm clusters
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.0
  logger: ^2.0.1
  cupertino_back_gesture: ^0.1.0
  intl: ^0.18.1
  json_theme: ^6.2.3
  local_auth: ^2.1.6
  dartssh2: ^2.8.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  curved_progress_bar: ^1.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  xterm: ^3.5.0
  file_picker: ^5.5.0
  xml2json: ^6.2.0
  expandable_widgets: ^1.0.3+1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/arimo/Arimo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arimo/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arimo/Arimo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/arimo/Arimo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true